-- MySQL Script generated by MySQL Workbench
-- Fri Apr  3 15:54:27 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema circlelabs
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema circlelabs
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `circlelabs` DEFAULT CHARACTER SET utf8mb4 ;
USE `circlelabs` ;

-- -----------------------------------------------------
-- Table `circlelabs`.`Role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `circlelabs`.`Role` ;

CREATE TABLE IF NOT EXISTS `circlelabs`.`Role` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `access_level` INT(1) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `name_UNIQUE` ON `circlelabs`.`Role` (`name` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `circlelabs`.`Location`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `circlelabs`.`Location` ;

CREATE TABLE IF NOT EXISTS `circlelabs`.`Location` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `address_line` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `postcode` VARCHAR(45) NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `isactive` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `address_line_one_UNIQUE` ON `circlelabs`.`Location` (`address_line` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `circlelabs`.`Person`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `circlelabs`.`Person` ;

CREATE TABLE IF NOT EXISTS `circlelabs`.`Person` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `dob` DATE NULL,
  `gender` TINYINT(1) NULL,
  `email` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(15) NOT NULL,
  `address` INT NOT NULL,
  `role` INT NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `isactive` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `person_role_fk`
    FOREIGN KEY (`role`)
    REFERENCES `circlelabs`.`Role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `person_location_fk`
    FOREIGN KEY (`address`)
    REFERENCES `circlelabs`.`Location` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `person_role_fk_idx` ON `circlelabs`.`Person` (`role` ASC) VISIBLE;

CREATE INDEX `Person_location_fk_idx` ON `circlelabs`.`Person` (`address` ASC) VISIBLE;

CREATE UNIQUE INDEX `username_UNIQUE` ON `circlelabs`.`Person` (`username` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `circlelabs`.`Appointment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `circlelabs`.`Appointment` ;

CREATE TABLE IF NOT EXISTS `circlelabs`.`Appointment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `desciption` VARCHAR(45) NOT NULL,
  `patient` INT NOT NULL,
  `staff_member` INT NOT NULL,
  `date_time` DATETIME NOT NULL,
  `location` INT NOT NULL,
  `duration` INT(5) NOT NULL,
  `isactive` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `appointment_patient_fk`
    FOREIGN KEY (`patient`)
    REFERENCES `circlelabs`.`Person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `appointment_staff_member_fk`
    FOREIGN KEY (`staff_member`)
    REFERENCES `circlelabs`.`Person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `appointment_location_fk`
    FOREIGN KEY (`location`)
    REFERENCES `circlelabs`.`Location` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `appointment_patient_fk_idx` ON `circlelabs`.`Appointment` (`patient` ASC) VISIBLE;

CREATE INDEX `appointment_staff_member_fk_idx` ON `circlelabs`.`Appointment` (`staff_member` ASC) VISIBLE;

CREATE INDEX `appointment_location_fk_idx` ON `circlelabs`.`Appointment` (`location` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `circlelabs`.`Prescription`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `circlelabs`.`Prescription` ;

CREATE TABLE IF NOT EXISTS `circlelabs`.`Prescription` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `patient` INT NOT NULL,
  `date` DATE NOT NULL,
  `quantity` INT(3) NOT NULL,
  `location` INT NOT NULL,
  `isactive` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `prescription_patient_fk`
    FOREIGN KEY (`patient`)
    REFERENCES `circlelabs`.`Person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `prescription_location_fk`
    FOREIGN KEY (`location`)
    REFERENCES `circlelabs`.`Location` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `prescription_patient_fk_idx` ON `circlelabs`.`Prescription` (`patient` ASC) VISIBLE;

CREATE INDEX `prescription_location_fk_idx` ON `circlelabs`.`Prescription` (`location` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `circlelabs`.`Drug`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `circlelabs`.`Drug` ;

CREATE TABLE IF NOT EXISTS `circlelabs`.`Drug` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(300) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `name_UNIQUE` ON `circlelabs`.`Drug` (`name` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `circlelabs`.`Treatment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `circlelabs`.`Treatment` ;

CREATE TABLE IF NOT EXISTS `circlelabs`.`Treatment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(300) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `name_UNIQUE` ON `circlelabs`.`Treatment` (`name` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `circlelabs`.`Disease`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `circlelabs`.`Disease` ;

CREATE TABLE IF NOT EXISTS `circlelabs`.`Disease` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(300) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `name_UNIQUE` ON `circlelabs`.`Disease` (`name` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `circlelabs`.`Symptom`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `circlelabs`.`Symptom` ;

CREATE TABLE IF NOT EXISTS `circlelabs`.`Symptom` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(300) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `name_UNIQUE` ON `circlelabs`.`Symptom` (`name` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `circlelabs`.`Report`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `circlelabs`.`Report` ;

CREATE TABLE IF NOT EXISTS `circlelabs`.`Report` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(300) NOT NULL,
  `requester` INT NOT NULL,
  `approved` TINYINT(1) NULL,
  `max_age` INT(3) NULL,
  `min_age` INT(3) NULL,
  `male` TINYINT(1) NULL,
  `female` TINYINT(1) NULL,
  `disease` INT NULL,
  `isactive` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `report_requester_fk`
    FOREIGN KEY (`requester`)
    REFERENCES `circlelabs`.`Person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `report_disease_fk`
    FOREIGN KEY (`disease`)
    REFERENCES `circlelabs`.`Disease` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `report_requester_fk_idx` ON `circlelabs`.`Report` (`requester` ASC) VISIBLE;

CREATE INDEX `report_disease_fk_idx` ON `circlelabs`.`Report` (`disease` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `circlelabs`.`Drug_Prescription_Link`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `circlelabs`.`Drug_Prescription_Link` ;

CREATE TABLE IF NOT EXISTS `circlelabs`.`Drug_Prescription_Link` (
  `drug` INT NOT NULL,
  `prescription` INT NOT NULL,
  PRIMARY KEY (`drug`, `prescription`),
  CONSTRAINT `drug_prescription_link_drug_fk`
    FOREIGN KEY (`drug`)
    REFERENCES `circlelabs`.`Drug` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `drug_prescription_link_prescription_fk`
    FOREIGN KEY (`prescription`)
    REFERENCES `circlelabs`.`Prescription` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `drug_prescription_link_prescription_fk_idx` ON `circlelabs`.`Drug_Prescription_Link` (`prescription` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `circlelabs`.`Drug_Treatment_Link`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `circlelabs`.`Drug_Treatment_Link` ;

CREATE TABLE IF NOT EXISTS `circlelabs`.`Drug_Treatment_Link` (
  `drug` INT NOT NULL,
  `treatment` INT NOT NULL,
  PRIMARY KEY (`drug`, `treatment`),
  CONSTRAINT `drug_treatment_link_drug_fk`
    FOREIGN KEY (`drug`)
    REFERENCES `circlelabs`.`Drug` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `drug_treatment_link_treatment_fk`
    FOREIGN KEY (`treatment`)
    REFERENCES `circlelabs`.`Treatment` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `drug_treatment_link_treatment_fk_idx` ON `circlelabs`.`Drug_Treatment_Link` (`treatment` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `circlelabs`.`Disease_Treatment_Link`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `circlelabs`.`Disease_Treatment_Link` ;

CREATE TABLE IF NOT EXISTS `circlelabs`.`Disease_Treatment_Link` (
  `disease` INT NOT NULL,
  `treatment` INT NOT NULL,
  PRIMARY KEY (`disease`, `treatment`),
  CONSTRAINT `disease_treatment_link_disease_fk`
    FOREIGN KEY (`disease`)
    REFERENCES `circlelabs`.`Disease` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `disease_treatment_link_treatment_fk`
    FOREIGN KEY (`treatment`)
    REFERENCES `circlelabs`.`Treatment` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `disease_treatment_link_treatment_fk_idx` ON `circlelabs`.`Disease_Treatment_Link` (`treatment` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `circlelabs`.`Disease_Symptom_Link`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `circlelabs`.`Disease_Symptom_Link` ;

CREATE TABLE IF NOT EXISTS `circlelabs`.`Disease_Symptom_Link` (
  `disease` INT NOT NULL,
  `symptom` INT NOT NULL,
  PRIMARY KEY (`disease`, `symptom`),
  CONSTRAINT `disease_symptom_link_disease_fk`
    FOREIGN KEY (`disease`)
    REFERENCES `circlelabs`.`Disease` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `disease_symptom_link_symptom_fk`
    FOREIGN KEY (`symptom`)
    REFERENCES `circlelabs`.`Symptom` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `disease_symptom_link_symptom_fk_idx` ON `circlelabs`.`Disease_Symptom_Link` (`symptom` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `circlelabs`.`Disease_Person_Link`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `circlelabs`.`Disease_Person_Link` ;

CREATE TABLE IF NOT EXISTS `circlelabs`.`Disease_Person_Link` (
  `disease` INT NOT NULL,
  `person` INT NOT NULL,
  PRIMARY KEY (`disease`, `person`),
  CONSTRAINT `disease_person_link_disease_fk`
    FOREIGN KEY (`disease`)
    REFERENCES `circlelabs`.`Disease` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `disease_person_link_person_fk`
    FOREIGN KEY (`person`)
    REFERENCES `circlelabs`.`Person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `disease_person_link_person_fk_idx` ON `circlelabs`.`Disease_Person_Link` (`person` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `circlelabs`.`Role`
-- -----------------------------------------------------
START TRANSACTION;
USE `circlelabs`;
INSERT INTO `circlelabs`.`Role` (`id`, `name`, `access_level`) VALUES (, 'Admin', 9);
INSERT INTO `circlelabs`.`Role` (`id`, `name`, `access_level`) VALUES (, 'Doctor', 9);
INSERT INTO `circlelabs`.`Role` (`id`, `name`, `access_level`) VALUES (, 'Government', 1);
INSERT INTO `circlelabs`.`Role` (`id`, `name`, `access_level`) VALUES (, 'Nurse', 8);
INSERT INTO `circlelabs`.`Role` (`id`, `name`, `access_level`) VALUES (, 'Patient', 0);
INSERT INTO `circlelabs`.`Role` (`id`, `name`, `access_level`) VALUES (, 'Pharmacy', 1);
INSERT INTO `circlelabs`.`Role` (`id`, `name`, `access_level`) VALUES (, 'Regulatory Body', 1);
INSERT INTO `circlelabs`.`Role` (`id`, `name`, `access_level`) VALUES (, 'Research Company', 1);
INSERT INTO `circlelabs`.`Role` (`id`, `name`, `access_level`) VALUES (, 'Staff', 7);

COMMIT;


-- -----------------------------------------------------
-- Data for table `circlelabs`.`Location`
-- -----------------------------------------------------
START TRANSACTION;
USE `circlelabs`;
INSERT INTO `circlelabs`.`Location` (`id`, `address_line`, `city`, `postcode`, `type`, `isactive`) VALUES (, '1 London Road', 'Southampton', 'SO16 7GP', 'Home', 1);
INSERT INTO `circlelabs`.`Location` (`id`, `address_line`, `city`, `postcode`, `type`, `isactive`) VALUES (, '2 London Road', 'Southampton', 'SO16 7GP', 'Home', 1);
INSERT INTO `circlelabs`.`Location` (`id`, `address_line`, `city`, `postcode`, `type`, `isactive`) VALUES (, '3 London Road', 'Southampton', 'SO16 7GP', 'Home', 1);
INSERT INTO `circlelabs`.`Location` (`id`, `address_line`, `city`, `postcode`, `type`, `isactive`) VALUES (, '4 London Road', 'Southampton', 'SO16 7GP', 'Home', 1);
INSERT INTO `circlelabs`.`Location` (`id`, `address_line`, `city`, `postcode`, `type`, `isactive`) VALUES (, '5 London Road', 'Southampton', 'SO16 7GP', 'Home', 1);
INSERT INTO `circlelabs`.`Location` (`id`, `address_line`, `city`, `postcode`, `type`, `isactive`) VALUES (, '6 London Road', 'Southampton', 'SO16 7GP', 'Home', 1);
INSERT INTO `circlelabs`.`Location` (`id`, `address_line`, `city`, `postcode`, `type`, `isactive`) VALUES (, '7 London Road', 'Southampton', 'SO16 7GP', 'Home', 1);
INSERT INTO `circlelabs`.`Location` (`id`, `address_line`, `city`, `postcode`, `type`, `isactive`) VALUES (, '8 London Road', 'Southampton', 'SO16 7GP', 'Home', 1);
INSERT INTO `circlelabs`.`Location` (`id`, `address_line`, `city`, `postcode`, `type`, `isactive`) VALUES (, '9 London Road', 'Southampton', 'SO16 7GP', 'Home', 1);
INSERT INTO `circlelabs`.`Location` (`id`, `address_line`, `city`, `postcode`, `type`, `isactive`) VALUES (, '10 London Road', 'Southampton', 'SO16 7GP', 'Home', 1);
INSERT INTO `circlelabs`.`Location` (`id`, `address_line`, `city`, `postcode`, `type`, `isactive`) VALUES (, '10 The High Street', 'Southampton', 'SO19 5RV', 'Pharmacy', 1);
INSERT INTO `circlelabs`.`Location` (`id`, `address_line`, `city`, `postcode`, `type`, `isactive`) VALUES (, '11 Rolling Road', 'Southampton', 'SO10 2TP', 'Pharmacy', 1);
INSERT INTO `circlelabs`.`Location` (`id`, `address_line`, `city`, `postcode`, `type`, `isactive`) VALUES (, '12 Sandpark Square', 'Southampton', 'SO16 4RL', 'Surgery', 1);
INSERT INTO `circlelabs`.`Location` (`id`, `address_line`, `city`, `postcode`, `type`, `isactive`) VALUES (, '13 Java Lane', 'Southampton', 'SO16 7GP', 'Surgery', 1);
INSERT INTO `circlelabs`.`Location` (`id`, `address_line`, `city`, `postcode`, `type`, `isactive`) VALUES (, '14 Cresent Place', 'Southampton', 'SO01 9UI', 'Hospital', 1);
INSERT INTO `circlelabs`.`Location` (`id`, `address_line`, `city`, `postcode`, `type`, `isactive`) VALUES (, '15 London Road', 'Southampton', 'SO23 6YP', 'Hospital', 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `circlelabs`.`Person`
-- -----------------------------------------------------
START TRANSACTION;
USE `circlelabs`;
INSERT INTO `circlelabs`.`Person` (`id`, `first_name`, `last_name`, `dob`, `gender`, `email`, `phone`, `address`, `role`, `username`, `password`, `isactive`) VALUES (, 'Robin', 'Wright', '08/04/1966', 1, 'rw@gmail.com', '07771111111', 1, 1, 'robinwright', 'rw123', 1);
INSERT INTO `circlelabs`.`Person` (`id`, `first_name`, `last_name`, `dob`, `gender`, `email`, `phone`, `address`, `role`, `username`, `password`, `isactive`) VALUES (, 'Tom', 'Cruise', '03/07/1962', 0, 'tc@gmail.com', '07772222222', 2, 2, 'tomcruise', 'tc123', 1);
INSERT INTO `circlelabs`.`Person` (`id`, `first_name`, `last_name`, `dob`, `gender`, `email`, `phone`, `address`, `role`, `username`, `password`, `isactive`) VALUES (, 'Matthew', 'Perry', '19/08/1969', 0, 'mp@gmail.com', '07773333333', 3, 3, 'matthewperry', 'mp123', 1);
INSERT INTO `circlelabs`.`Person` (`id`, `first_name`, `last_name`, `dob`, `gender`, `email`, `phone`, `address`, `role`, `username`, `password`, `isactive`) VALUES (, 'Andy', 'Samberg', '18/08/1978', 0, 'as@gmail.com', '07774444444', 4, 4, 'andysamberg', 'as123', 1);
INSERT INTO `circlelabs`.`Person` (`id`, `first_name`, `last_name`, `dob`, `gender`, `email`, `phone`, `address`, `role`, `username`, `password`, `isactive`) VALUES (, 'Jessica', 'Alba', '28/04/1981', 1, 'ja@gmail.com', '07775555555', 5, 5, 'jessicaalba', 'ja123', 1);
INSERT INTO `circlelabs`.`Person` (`id`, `first_name`, `last_name`, `dob`, `gender`, `email`, `phone`, `address`, `role`, `username`, `password`, `isactive`) VALUES (, 'Emma', 'Thompson', '15/04/1959', 1, 'et@gmail.com', '07776666666', 6, 6, 'emmathompson', 'et123', 1);
INSERT INTO `circlelabs`.`Person` (`id`, `first_name`, `last_name`, `dob`, `gender`, `email`, `phone`, `address`, `role`, `username`, `password`, `isactive`) VALUES (, 'Billy', 'Zane', '24/02/1966', 0, 'bz@gmail.com', '07777777777', 7, 7, 'billyzane', 'bz123', 1);
INSERT INTO `circlelabs`.`Person` (`id`, `first_name`, `last_name`, `dob`, `gender`, `email`, `phone`, `address`, `role`, `username`, `password`, `isactive`) VALUES (, 'Emma', 'Stone', '06/11/1988', 1, 'es@gmail.com', '07778888888', 8, 8, 'emmastone', 'es123', 1);
INSERT INTO `circlelabs`.`Person` (`id`, `first_name`, `last_name`, `dob`, `gender`, `email`, `phone`, `address`, `role`, `username`, `password`, `isactive`) VALUES (, 'Megan', 'Fox', '16/05/1986', 1, 'mf@gmail.com', '07779999999', 9, 9, 'meganfox', 'mf123', 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `circlelabs`.`Appointment`
-- -----------------------------------------------------
START TRANSACTION;
USE `circlelabs`;
INSERT INTO `circlelabs`.`Appointment` (`id`, `desciption`, `patient`, `staff_member`, `date_time`, `location`, `duration`, `isactive`) VALUES (, 'GP Appointment', 6, 1, '2020-05-01 09:00:00', 14, 10, 1);
INSERT INTO `circlelabs`.`Appointment` (`id`, `desciption`, `patient`, `staff_member`, `date_time`, `location`, `duration`, `isactive`) VALUES (, 'Nurse Appointment', 6, 5, '2020-05-02 09:00:00', 14, 5, 1);
INSERT INTO `circlelabs`.`Appointment` (`id`, `desciption`, `patient`, `staff_member`, `date_time`, `location`, `duration`, `isactive`) VALUES (, 'Nurse Appointment', 6, 5, '2020-05-03 09:00:00', 14, 5, 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `circlelabs`.`Prescription`
-- -----------------------------------------------------
START TRANSACTION;
USE `circlelabs`;
INSERT INTO `circlelabs`.`Prescription` (`id`, `patient`, `date`, `quantity`, `location`, `isactive`) VALUES (, 6, '2020-04-01', 14, 11, 1);
INSERT INTO `circlelabs`.`Prescription` (`id`, `patient`, `date`, `quantity`, `location`, `isactive`) VALUES (, 6, '2020-04-02', 14, 11, 1);
INSERT INTO `circlelabs`.`Prescription` (`id`, `patient`, `date`, `quantity`, `location`, `isactive`) VALUES (, 6, '2020-04-03', 14, 11, 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `circlelabs`.`Drug`
-- -----------------------------------------------------
START TRANSACTION;
USE `circlelabs`;
INSERT INTO `circlelabs`.`Drug` (`id`, `name`) VALUES (, 'amoxicillin');
INSERT INTO `circlelabs`.`Drug` (`id`, `name`) VALUES (, 'doxycycline');
INSERT INTO `circlelabs`.`Drug` (`id`, `name`) VALUES (, 'cephalexin');
INSERT INTO `circlelabs`.`Drug` (`id`, `name`) VALUES (, 'ciprofloxacin');
INSERT INTO `circlelabs`.`Drug` (`id`, `name`) VALUES (, 'clindamycin');
INSERT INTO `circlelabs`.`Drug` (`id`, `name`) VALUES (, 'metronidazole');
INSERT INTO `circlelabs`.`Drug` (`id`, `name`) VALUES (, 'azithromycin');

COMMIT;


-- -----------------------------------------------------
-- Data for table `circlelabs`.`Treatment`
-- -----------------------------------------------------
START TRANSACTION;
USE `circlelabs`;
INSERT INTO `circlelabs`.`Treatment` (`id`, `name`) VALUES (, 'painkiller');
INSERT INTO `circlelabs`.`Treatment` (`id`, `name`) VALUES (, 'ankle support');
INSERT INTO `circlelabs`.`Treatment` (`id`, `name`) VALUES (, 'x-ray');
INSERT INTO `circlelabs`.`Treatment` (`id`, `name`) VALUES (, 'supportive boot');
INSERT INTO `circlelabs`.`Treatment` (`id`, `name`) VALUES (, 'splint or plaster');
INSERT INTO `circlelabs`.`Treatment` (`id`, `name`) VALUES (, 'surgery');
INSERT INTO `circlelabs`.`Treatment` (`id`, `name`) VALUES (, 'resting your heel');
INSERT INTO `circlelabs`.`Treatment` (`id`, `name`) VALUES (, 'regular stretching');
INSERT INTO `circlelabs`.`Treatment` (`id`, `name`) VALUES (, 'wearing well fitted shoes');
INSERT INTO `circlelabs`.`Treatment` (`id`, `name`) VALUES (, 'using supportive devices');
INSERT INTO `circlelabs`.`Treatment` (`id`, `name`) VALUES (, 'losing weight');
INSERT INTO `circlelabs`.`Treatment` (`id`, `name`) VALUES (, 'taking regular exercise');
INSERT INTO `circlelabs`.`Treatment` (`id`, `name`) VALUES (, 'raising your legs three to four times a day');
INSERT INTO `circlelabs`.`Treatment` (`id`, `name`) VALUES (, 'avoiding standing for long periods of time');
INSERT INTO `circlelabs`.`Treatment` (`id`, `name`) VALUES (, 'lifestyle changes');
INSERT INTO `circlelabs`.`Treatment` (`id`, `name`) VALUES (, 'medication');
INSERT INTO `circlelabs`.`Treatment` (`id`, `name`) VALUES (, 'price therapy');
INSERT INTO `circlelabs`.`Treatment` (`id`, `name`) VALUES (, 'avoiding harm');
INSERT INTO `circlelabs`.`Treatment` (`id`, `name`) VALUES (, 'physiotherapy');
INSERT INTO `circlelabs`.`Treatment` (`id`, `name`) VALUES (, 'self-help measures');
INSERT INTO `circlelabs`.`Treatment` (`id`, `name`) VALUES (, 'emollients');
INSERT INTO `circlelabs`.`Treatment` (`id`, `name`) VALUES (, 'topical corticosteroids');
INSERT INTO `circlelabs`.`Treatment` (`id`, `name`) VALUES (, 'compression stockings');
INSERT INTO `circlelabs`.`Treatment` (`id`, `name`) VALUES (, 'ice pack');
INSERT INTO `circlelabs`.`Treatment` (`id`, `name`) VALUES (, 'immobilisation');
INSERT INTO `circlelabs`.`Treatment` (`id`, `name`) VALUES (, 'reduction');

COMMIT;


-- -----------------------------------------------------
-- Data for table `circlelabs`.`Disease`
-- -----------------------------------------------------
START TRANSACTION;
USE `circlelabs`;
INSERT INTO `circlelabs`.`Disease` (`id`, `name`) VALUES (, 'broken ankle');
INSERT INTO `circlelabs`.`Disease` (`id`, `name`) VALUES (, 'heel pain');
INSERT INTO `circlelabs`.`Disease` (`id`, `name`) VALUES (, 'oedema');
INSERT INTO `circlelabs`.`Disease` (`id`, `name`) VALUES (, 'restless legs syndrome');
INSERT INTO `circlelabs`.`Disease` (`id`, `name`) VALUES (, 'sprains and strains');
INSERT INTO `circlelabs`.`Disease` (`id`, `name`) VALUES (, 'varicose eczema');
INSERT INTO `circlelabs`.`Disease` (`id`, `name`) VALUES (, 'baker\'s cyst');
INSERT INTO `circlelabs`.`Disease` (`id`, `name`) VALUES (, 'broken leg');

COMMIT;


-- -----------------------------------------------------
-- Data for table `circlelabs`.`Symptom`
-- -----------------------------------------------------
START TRANSACTION;
USE `circlelabs`;
INSERT INTO `circlelabs`.`Symptom` (`id`, `name`) VALUES (, 'severe pain');
INSERT INTO `circlelabs`.`Symptom` (`id`, `name`) VALUES (, 'swelling');
INSERT INTO `circlelabs`.`Symptom` (`id`, `name`) VALUES (, 'bruising');
INSERT INTO `circlelabs`.`Symptom` (`id`, `name`) VALUES (, 'difficulty moving foot');
INSERT INTO `circlelabs`.`Symptom` (`id`, `name`) VALUES (, 'difficulty putting weight on foot');
INSERT INTO `circlelabs`.`Symptom` (`id`, `name`) VALUES (, 'the ankle being an odd shape');
INSERT INTO `circlelabs`.`Symptom` (`id`, `name`) VALUES (, 'a snap or grinding noise');
INSERT INTO `circlelabs`.`Symptom` (`id`, `name`) VALUES (, 'bleeding');
INSERT INTO `circlelabs`.`Symptom` (`id`, `name`) VALUES (, 'pain in heel');
INSERT INTO `circlelabs`.`Symptom` (`id`, `name`) VALUES (, 'skin discolouration');
INSERT INTO `circlelabs`.`Symptom` (`id`, `name`) VALUES (, 'pitting oedema');
INSERT INTO `circlelabs`.`Symptom` (`id`, `name`) VALUES (, 'aching tender limbs');
INSERT INTO `circlelabs`.`Symptom` (`id`, `name`) VALUES (, 'stiff joints');
INSERT INTO `circlelabs`.`Symptom` (`id`, `name`) VALUES (, 'weight gain');
INSERT INTO `circlelabs`.`Symptom` (`id`, `name`) VALUES (, 'creepy-crawly feeling');
INSERT INTO `circlelabs`.`Symptom` (`id`, `name`) VALUES (, 'feeling different');
INSERT INTO `circlelabs`.`Symptom` (`id`, `name`) VALUES (, 'a painful cramping sensation in the legs');
INSERT INTO `circlelabs`.`Symptom` (`id`, `name`) VALUES (, 'tingling');
INSERT INTO `circlelabs`.`Symptom` (`id`, `name`) VALUES (, 'burning');
INSERT INTO `circlelabs`.`Symptom` (`id`, `name`) VALUES (, 'itching');
INSERT INTO `circlelabs`.`Symptom` (`id`, `name`) VALUES (, 'throbbing');
INSERT INTO `circlelabs`.`Symptom` (`id`, `name`) VALUES (, 'pain around the affected joint');
INSERT INTO `circlelabs`.`Symptom` (`id`, `name`) VALUES (, 'inability to put weight on it');
INSERT INTO `circlelabs`.`Symptom` (`id`, `name`) VALUES (, 'inability to use the joint normally');
INSERT INTO `circlelabs`.`Symptom` (`id`, `name`) VALUES (, 'bruising and tenderness');
INSERT INTO `circlelabs`.`Symptom` (`id`, `name`) VALUES (, 'redness');
INSERT INTO `circlelabs`.`Symptom` (`id`, `name`) VALUES (, 'pain in the affected muscle at rest');
INSERT INTO `circlelabs`.`Symptom` (`id`, `name`) VALUES (, 'pain in the muscle or associated joint during use');
INSERT INTO `circlelabs`.`Symptom` (`id`, `name`) VALUES (, 'muscle spasms');
INSERT INTO `circlelabs`.`Symptom` (`id`, `name`) VALUES (, 'itchy skin');
INSERT INTO `circlelabs`.`Symptom` (`id`, `name`) VALUES (, 'red skin');
INSERT INTO `circlelabs`.`Symptom` (`id`, `name`) VALUES (, 'dry and flaky skin');
INSERT INTO `circlelabs`.`Symptom` (`id`, `name`) VALUES (, 'scaly or crusty skin');
INSERT INTO `circlelabs`.`Symptom` (`id`, `name`) VALUES (, 'swollen skin');
INSERT INTO `circlelabs`.`Symptom` (`id`, `name`) VALUES (, 'brown discolouration of the skin');
INSERT INTO `circlelabs`.`Symptom` (`id`, `name`) VALUES (, 'lipodermatosclerosis');
INSERT INTO `circlelabs`.`Symptom` (`id`, `name`) VALUES (, 'small white scars');
INSERT INTO `circlelabs`.`Symptom` (`id`, `name`) VALUES (, 'pain');
INSERT INTO `circlelabs`.`Symptom` (`id`, `name`) VALUES (, 'eczema affecting other parts of the body');
INSERT INTO `circlelabs`.`Symptom` (`id`, `name`) VALUES (, 'pain in the calf');
INSERT INTO `circlelabs`.`Symptom` (`id`, `name`) VALUES (, 'a build-up of fluid around the knee');
INSERT INTO `circlelabs`.`Symptom` (`id`, `name`) VALUES (, 'occasional locking or clicking in the knee joint');
INSERT INTO `circlelabs`.`Symptom` (`id`, `name`) VALUES (, 'pain in the knee');
INSERT INTO `circlelabs`.`Symptom` (`id`, `name`) VALUES (, 'severely painful leg');
INSERT INTO `circlelabs`.`Symptom` (`id`, `name`) VALUES (, 'swollen leg');
INSERT INTO `circlelabs`.`Symptom` (`id`, `name`) VALUES (, 'bruised');

COMMIT;


-- -----------------------------------------------------
-- Data for table `circlelabs`.`Report`
-- -----------------------------------------------------
START TRANSACTION;
USE `circlelabs`;
INSERT INTO `circlelabs`.`Report` (`id`, `name`, `requester`, `approved`, `max_age`, `min_age`, `male`, `female`, `disease`, `isactive`) VALUES (, 'Broken Ankle Men Only', 9, 1, NULL, NULL, 1, NULL, 1, DEFAULT);
INSERT INTO `circlelabs`.`Report` (`id`, `name`, `requester`, `approved`, `max_age`, `min_age`, `male`, `female`, `disease`, `isactive`) VALUES (, 'Broken Ankle Women Only', 9, 0, NULL, NULL, NULL, 1, 1, DEFAULT);
INSERT INTO `circlelabs`.`Report` (`id`, `name`, `requester`, `approved`, `max_age`, `min_age`, `male`, `female`, `disease`, `isactive`) VALUES (, 'Heel Pain', 8, 1, NULL, NULL, NULL, NULL, 2, DEFAULT);

COMMIT;


-- -----------------------------------------------------
-- Data for table `circlelabs`.`Drug_Prescription_Link`
-- -----------------------------------------------------
START TRANSACTION;
USE `circlelabs`;
INSERT INTO `circlelabs`.`Drug_Prescription_Link` (`drug`, `prescription`) VALUES (1, 1);
INSERT INTO `circlelabs`.`Drug_Prescription_Link` (`drug`, `prescription`) VALUES (2, 2);
INSERT INTO `circlelabs`.`Drug_Prescription_Link` (`drug`, `prescription`) VALUES (3, 3);

COMMIT;


-- -----------------------------------------------------
-- Data for table `circlelabs`.`Drug_Treatment_Link`
-- -----------------------------------------------------
START TRANSACTION;
USE `circlelabs`;
INSERT INTO `circlelabs`.`Drug_Treatment_Link` (`drug`, `treatment`) VALUES (1, 1);
INSERT INTO `circlelabs`.`Drug_Treatment_Link` (`drug`, `treatment`) VALUES (2, 1);
INSERT INTO `circlelabs`.`Drug_Treatment_Link` (`drug`, `treatment`) VALUES (3, 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `circlelabs`.`Disease_Treatment_Link`
-- -----------------------------------------------------
START TRANSACTION;
USE `circlelabs`;
INSERT INTO `circlelabs`.`Disease_Treatment_Link` (`disease`, `treatment`) VALUES (1, 1);
INSERT INTO `circlelabs`.`Disease_Treatment_Link` (`disease`, `treatment`) VALUES (1, 2);
INSERT INTO `circlelabs`.`Disease_Treatment_Link` (`disease`, `treatment`) VALUES (1, 3);
INSERT INTO `circlelabs`.`Disease_Treatment_Link` (`disease`, `treatment`) VALUES (1, 4);
INSERT INTO `circlelabs`.`Disease_Treatment_Link` (`disease`, `treatment`) VALUES (1, 5);
INSERT INTO `circlelabs`.`Disease_Treatment_Link` (`disease`, `treatment`) VALUES (1, 6);
INSERT INTO `circlelabs`.`Disease_Treatment_Link` (`disease`, `treatment`) VALUES (2, 7);
INSERT INTO `circlelabs`.`Disease_Treatment_Link` (`disease`, `treatment`) VALUES (2, 8);
INSERT INTO `circlelabs`.`Disease_Treatment_Link` (`disease`, `treatment`) VALUES (2, 1);
INSERT INTO `circlelabs`.`Disease_Treatment_Link` (`disease`, `treatment`) VALUES (2, 9);
INSERT INTO `circlelabs`.`Disease_Treatment_Link` (`disease`, `treatment`) VALUES (2, 10);
INSERT INTO `circlelabs`.`Disease_Treatment_Link` (`disease`, `treatment`) VALUES (3, 11);
INSERT INTO `circlelabs`.`Disease_Treatment_Link` (`disease`, `treatment`) VALUES (3, 12);
INSERT INTO `circlelabs`.`Disease_Treatment_Link` (`disease`, `treatment`) VALUES (3, 13);
INSERT INTO `circlelabs`.`Disease_Treatment_Link` (`disease`, `treatment`) VALUES (3, 14);
INSERT INTO `circlelabs`.`Disease_Treatment_Link` (`disease`, `treatment`) VALUES (4, 15);
INSERT INTO `circlelabs`.`Disease_Treatment_Link` (`disease`, `treatment`) VALUES (4, 16);
INSERT INTO `circlelabs`.`Disease_Treatment_Link` (`disease`, `treatment`) VALUES (5, 17);
INSERT INTO `circlelabs`.`Disease_Treatment_Link` (`disease`, `treatment`) VALUES (5, 18);
INSERT INTO `circlelabs`.`Disease_Treatment_Link` (`disease`, `treatment`) VALUES (5, 1);
INSERT INTO `circlelabs`.`Disease_Treatment_Link` (`disease`, `treatment`) VALUES (5, 19);
INSERT INTO `circlelabs`.`Disease_Treatment_Link` (`disease`, `treatment`) VALUES (6, 20);
INSERT INTO `circlelabs`.`Disease_Treatment_Link` (`disease`, `treatment`) VALUES (6, 21);
INSERT INTO `circlelabs`.`Disease_Treatment_Link` (`disease`, `treatment`) VALUES (6, 22);
INSERT INTO `circlelabs`.`Disease_Treatment_Link` (`disease`, `treatment`) VALUES (6, 23);
INSERT INTO `circlelabs`.`Disease_Treatment_Link` (`disease`, `treatment`) VALUES (7, 1);
INSERT INTO `circlelabs`.`Disease_Treatment_Link` (`disease`, `treatment`) VALUES (7, 24);
INSERT INTO `circlelabs`.`Disease_Treatment_Link` (`disease`, `treatment`) VALUES (8, 25);
INSERT INTO `circlelabs`.`Disease_Treatment_Link` (`disease`, `treatment`) VALUES (8, 26);
INSERT INTO `circlelabs`.`Disease_Treatment_Link` (`disease`, `treatment`) VALUES (8, 6);

COMMIT;


-- -----------------------------------------------------
-- Data for table `circlelabs`.`Disease_Symptom_Link`
-- -----------------------------------------------------
START TRANSACTION;
USE `circlelabs`;
INSERT INTO `circlelabs`.`Disease_Symptom_Link` (`disease`, `symptom`) VALUES (1, 1);
INSERT INTO `circlelabs`.`Disease_Symptom_Link` (`disease`, `symptom`) VALUES (1, 2);
INSERT INTO `circlelabs`.`Disease_Symptom_Link` (`disease`, `symptom`) VALUES (1, 3);
INSERT INTO `circlelabs`.`Disease_Symptom_Link` (`disease`, `symptom`) VALUES (1, 4);
INSERT INTO `circlelabs`.`Disease_Symptom_Link` (`disease`, `symptom`) VALUES (1, 5);
INSERT INTO `circlelabs`.`Disease_Symptom_Link` (`disease`, `symptom`) VALUES (1, 6);
INSERT INTO `circlelabs`.`Disease_Symptom_Link` (`disease`, `symptom`) VALUES (1, 7);
INSERT INTO `circlelabs`.`Disease_Symptom_Link` (`disease`, `symptom`) VALUES (1, 8);
INSERT INTO `circlelabs`.`Disease_Symptom_Link` (`disease`, `symptom`) VALUES (2, 9);
INSERT INTO `circlelabs`.`Disease_Symptom_Link` (`disease`, `symptom`) VALUES (3, 10);
INSERT INTO `circlelabs`.`Disease_Symptom_Link` (`disease`, `symptom`) VALUES (3, 11);
INSERT INTO `circlelabs`.`Disease_Symptom_Link` (`disease`, `symptom`) VALUES (3, 12);
INSERT INTO `circlelabs`.`Disease_Symptom_Link` (`disease`, `symptom`) VALUES (3, 13);
INSERT INTO `circlelabs`.`Disease_Symptom_Link` (`disease`, `symptom`) VALUES (3, 14);
INSERT INTO `circlelabs`.`Disease_Symptom_Link` (`disease`, `symptom`) VALUES (4, 15);
INSERT INTO `circlelabs`.`Disease_Symptom_Link` (`disease`, `symptom`) VALUES (4, 16);
INSERT INTO `circlelabs`.`Disease_Symptom_Link` (`disease`, `symptom`) VALUES (4, 17);
INSERT INTO `circlelabs`.`Disease_Symptom_Link` (`disease`, `symptom`) VALUES (4, 18);
INSERT INTO `circlelabs`.`Disease_Symptom_Link` (`disease`, `symptom`) VALUES (4, 19);
INSERT INTO `circlelabs`.`Disease_Symptom_Link` (`disease`, `symptom`) VALUES (4, 20);
INSERT INTO `circlelabs`.`Disease_Symptom_Link` (`disease`, `symptom`) VALUES (4, 21);
INSERT INTO `circlelabs`.`Disease_Symptom_Link` (`disease`, `symptom`) VALUES (5, 22);
INSERT INTO `circlelabs`.`Disease_Symptom_Link` (`disease`, `symptom`) VALUES (5, 23);
INSERT INTO `circlelabs`.`Disease_Symptom_Link` (`disease`, `symptom`) VALUES (5, 2);
INSERT INTO `circlelabs`.`Disease_Symptom_Link` (`disease`, `symptom`) VALUES (5, 24);
INSERT INTO `circlelabs`.`Disease_Symptom_Link` (`disease`, `symptom`) VALUES (5, 25);
INSERT INTO `circlelabs`.`Disease_Symptom_Link` (`disease`, `symptom`) VALUES (5, 26);
INSERT INTO `circlelabs`.`Disease_Symptom_Link` (`disease`, `symptom`) VALUES (5, 27);
INSERT INTO `circlelabs`.`Disease_Symptom_Link` (`disease`, `symptom`) VALUES (5, 28);
INSERT INTO `circlelabs`.`Disease_Symptom_Link` (`disease`, `symptom`) VALUES (5, 29);
INSERT INTO `circlelabs`.`Disease_Symptom_Link` (`disease`, `symptom`) VALUES (6, 30);
INSERT INTO `circlelabs`.`Disease_Symptom_Link` (`disease`, `symptom`) VALUES (6, 31);
INSERT INTO `circlelabs`.`Disease_Symptom_Link` (`disease`, `symptom`) VALUES (6, 32);
INSERT INTO `circlelabs`.`Disease_Symptom_Link` (`disease`, `symptom`) VALUES (6, 33);
INSERT INTO `circlelabs`.`Disease_Symptom_Link` (`disease`, `symptom`) VALUES (6, 34);
INSERT INTO `circlelabs`.`Disease_Symptom_Link` (`disease`, `symptom`) VALUES (6, 35);
INSERT INTO `circlelabs`.`Disease_Symptom_Link` (`disease`, `symptom`) VALUES (6, 36);
INSERT INTO `circlelabs`.`Disease_Symptom_Link` (`disease`, `symptom`) VALUES (6, 37);
INSERT INTO `circlelabs`.`Disease_Symptom_Link` (`disease`, `symptom`) VALUES (6, 38);
INSERT INTO `circlelabs`.`Disease_Symptom_Link` (`disease`, `symptom`) VALUES (6, 39);
INSERT INTO `circlelabs`.`Disease_Symptom_Link` (`disease`, `symptom`) VALUES (7, 40);
INSERT INTO `circlelabs`.`Disease_Symptom_Link` (`disease`, `symptom`) VALUES (7, 41);
INSERT INTO `circlelabs`.`Disease_Symptom_Link` (`disease`, `symptom`) VALUES (7, 42);
INSERT INTO `circlelabs`.`Disease_Symptom_Link` (`disease`, `symptom`) VALUES (7, 43);
INSERT INTO `circlelabs`.`Disease_Symptom_Link` (`disease`, `symptom`) VALUES (8, 44);
INSERT INTO `circlelabs`.`Disease_Symptom_Link` (`disease`, `symptom`) VALUES (8, 45);
INSERT INTO `circlelabs`.`Disease_Symptom_Link` (`disease`, `symptom`) VALUES (8, 46);

COMMIT;


-- -----------------------------------------------------
-- Data for table `circlelabs`.`Disease_Person_Link`
-- -----------------------------------------------------
START TRANSACTION;
USE `circlelabs`;
INSERT INTO `circlelabs`.`Disease_Person_Link` (`disease`, `person`) VALUES (1, 6);
INSERT INTO `circlelabs`.`Disease_Person_Link` (`disease`, `person`) VALUES (2, 6);
INSERT INTO `circlelabs`.`Disease_Person_Link` (`disease`, `person`) VALUES (5, 6);

COMMIT;

